### ISSUE TITLE
회원가입 페이지 제작

### ISSUE THREAD

**Issue by hin6150** [likelionknu/apply-page-frontend#45]
- [x] 디자인 UI 구현
- [x] 회원 가입 페이지 기능 구현
    - React Hook Form 적용
- [x] 이메일 인증 구현
    - 3분 제한 타이머 
    - 재 전송은 30초 제한
- [ ] BE와 연동

**Comment by klmhyeonwoo** [comment]
· 사용자가 입력 시 값이 잘 입력 되었는지 확인할 수 있어야함
· 자릿 수가 고정된 부분들은 input의 maxLength 값을 고정시켜줘야함 (ex. 학번 9자리)
· 이메일을 모두 입력을 하지 않았음에도 불구하고, 이메일 보내기가 가능한 문제가 있음 (해결 요망)

**Comment by hin6150** [comment]
이메일 보내기, 인증하기 버튼을 누르지 않고 submit 시 오류 처리

올바르지 않거나, 30초가 지나지 않고 이메일 보낼경우 alert 처리

올바르게 이메일 인증시, 인종번호 탭 삭제 및 이메일 재설정 버튼 생성

이메일 인증 타이머 UI 수정
